### ISSUE TITLE
Export sur des grosses archives

### ISSUE THREAD

**Issue by lsagetlethias** [SocialGouv/archifiltre-mails#235]
### User Story

SocialGouv/archifiltre-mails#185

### Description du bug

Lorsque qu'on veut exporter avec n'importe quel type d'export une grosse archives (1Go par exemple), une erreur en dev apparaît : (exemple avec EML)
```
Error occurred in handler for 'pstExporter.event.exportMails': Error: Emails not found from given indexes.
      at PstExtractorModule.eval (webpack-internal:///./src/main/modules/PstExtractorModule.ts:140:23)
      at Generator.next (<anonymous>)
      at fulfilled (webpack-internal:///./src/main/modules/PstExtractorModule.ts:5:58)
 ```

### Étapes pour reproduire

1. Ouvrir le PST de 1.2Go (copie multiple de la boîte "Alquier"
2. Lancer l'export EML (ou autre)
3. Constater l'erreur

### Comportement attendu

Les exports doivent marcher et aussi peut-être être plus rapide ?

### Solution

1. Soit tout exporter dans le `fetcher` puis mettre en cache et récupérer depuis le module pour éviter la serialization
2. Soit exporter mail par mail depuis l'exporter pour enregistrer chaque EML. Le problème est que cette méthode est séquentielle.

### Liste des caractéristiques de votre machine

- dev adf94008607a73ec65847acad4980c304a6b85dd
- osx

### Version de l'application

next (à préciser dans les caratéristiques)

**Comment by lsagetlethias** [comment]
- la problématique vient des dossier avec des sous dossiers ET des mails en même temps, qui posent problème en amont à la génération des indexes lors de l'extract (`0 1 2 4 0 3` pour ceux sachent)
